In [1]:
# Import numpy and Version Check 
import numpy as np
np.__version__

'1.23.5'

In [2]:
# Declare a numpy array 
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
# Create an array 
P = np.arange(10)

In [4]:
## Access the array elements(Indexing and Slicing)
print(P)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
P[:3]

array([0, 1, 2])

In [6]:
print(P[0])

0


In [7]:
print(P[1])

1


In [8]:
print([-1])

[-1]


In [9]:
print(P[:])

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(P[1:-1])

[1 2 3 4 5 6 7 8]


In [11]:
## Reshape an array to a new format
a= np.array([1,2,3,4,5,6])
a.reshape(2,3)  ##  2 rows and 3 column format 

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Create specific type of arrays 

In [13]:
np.zeros(10, dtype = int) ## Array of all zeros 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10, dtype =float) ## array of all ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
## Array creation with array elements 

In [16]:
np.random.randint(1,10,9) ## Array with random integer elements 

array([3, 6, 6, 5, 3, 3, 6, 9, 2])

In [17]:
np.random.randint(1,10,(3,3)) ## No need to define number o array elements as 3*3 matris will have 9 elements

array([[9, 1, 5],
       [3, 4, 9],
       [1, 2, 7]])

In [18]:
np.random.randint(1,10,9).reshape(3,3) ## Can reshape 9 elements into 3*3 matrix

array([[9, 9, 2],
       [9, 6, 5],
       [1, 2, 9]])

In [19]:
np.random.random(10) ## Array with random float elements between 0 to 1

array([0.54047734, 0.97441156, 0.47970811, 0.99869889, 0.55143541,
       0.48178691, 0.96434373, 0.9990676 , 0.3698882 , 0.96092727])

In [20]:
np.random.random(10).reshape(5,2) # Reshaping the array to a new dimension

array([[0.57792429, 0.61601681],
       [0.23750028, 0.45808649],
       [0.55417283, 0.93860767],
       [0.58642868, 0.24505162],
       [0.84636788, 0.86731499]])

In [21]:
10* np.random.random(10) ## Array with float numbers between 1 to 10 

array([5.02245878, 2.47921283, 6.11464489, 4.07976078, 6.33106654,
       1.92006929, 7.71556124, 6.44630617, 7.90484443, 6.3963673 ])

In [22]:
np.sort(10* np.random.random(10)) ## np.sort sorts the array

array([1.76175951, 2.85924478, 2.93384172, 4.1380442 , 5.0659805 ,
       6.61056134, 6.65439049, 6.82882199, 7.88614719, 8.57177721])

In [23]:
np.sort(10* np.random.random(10).reshape(5,2)) ## Create a 2-D array and soort it 

array([[1.57048819, 2.15702844],
       [2.61723003, 8.08641877],
       [2.91266485, 9.05019716],
       [2.26790673, 7.96682722],
       [7.10749998, 9.48046874]])

In [24]:
np.linspace(0,10,5) ## linspace will create 5 elements from 0 to 10 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
s= np.linspace(1,20,5, dtype= int) ## creates 5 elements from 1 to 20 of integer type 

In [26]:
np.max(s)

20

In [27]:
np.arange(0,10,1) # Creates an array from 0 to 10 with a spacing of 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.min(s)

1

In [29]:
np.mean(s)

10.2

In [30]:
np.median(s)

10.0

In [31]:
## Array Math functions

In [32]:
x = ([1,2,3,4])
y = ([10,20,30,40])

In [33]:
np.add(x,y)

array([11, 22, 33, 44])

In [34]:
np.subtract(x,y)

array([ -9, -18, -27, -36])

In [35]:
np.multiply(x,y)

array([ 10,  40,  90, 160])

In [36]:
np.divide(x,y)

array([0.1, 0.1, 0.1, 0.1])

In [37]:
np.concatenate((x,y), axis=0)

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [38]:
x+y

[1, 2, 3, 4, 10, 20, 30, 40]

In [39]:
p = ([[1,2],[3,4]])
q= ([[5,6],[0,1]])
print(p)
print(q)

[[1, 2], [3, 4]]
[[5, 6], [0, 1]]


In [40]:
np.concatenate((p,q), axis=0) ##  Concatenated row wise. Added to row (axis=0 means row)

array([[1, 2],
       [3, 4],
       [5, 6],
       [0, 1]])

In [41]:
np.concatenate((p,q), axis=1) ##  Concatenated column wise. Added to column (axis=1 means column)

array([[1, 2, 5, 6],
       [3, 4, 0, 1]])